In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
# 4 samples/observations and 2 variables/features
X = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
print(X)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]


In [3]:
# the scaler object (model)
scaler = StandardScaler()

In [4]:
# fit and transform the data
scaled_data = scaler.fit_transform(X)
print(scaled_data)

[[-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1.  1.]]


In [5]:
scaled_data.mean(axis = 0)

array([0., 0.])

In [6]:
scaled_data.std(axis = 0)

array([1., 1.])